### ISSUE TITLE
make all  error~

### ISSUE THREAD

**Issue by 0x7e-1sq** [h3xduck/TripleCross#39]
Hey, I have this error when I make all, how can I solve it, my environment is kali Thank you

libbpf: elf: skipping unrecognized data section(17) .rodata.str1.1
  CC       .output/kit.o
user/kit.c:29:10: fatal error: include/utils/files/path.h: No such file or directory
   29 | #include "include/utils/files/path.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:97: .output/kit.o] Error 1
rm .output/kit.bpf.o

**Comment by h3xduck** [comment]
Hey, that's my fault, my build had some extra files with other stuff we removed from the repo in the final release.

I'll push a fix in some hours, for now remove the following includes from src/user/kit.c

#include "include/utils/files/path.h" 
#include "include/utils/strings/regex.h" 
#include "include/utils/structures/fdlist.h"

That should make the trick for the compilation, but since you mentioned to be using Kali, note that this rootkit has been developed and tested in Ubuntu 21.04, so I cannot guarantee all rootkit modules to work (in particular, the library injection one). 

You can check the Ubuntu and kernel versions we tested in section 1.2 of the thesis document, I'll write it on the README too.

**Comment by 0x7e-1sq** [comment]
Hello, I tried to compile on ubuntu21.04 today, but the problem still occurs, please help me, thanks.

**Comment by h3xduck** [comment]
It should be sho

**Comment by h3xduck** [comment]
It should be working now (and also before with the modification I suggested). Are you getting a different build error?

**Comment by 0x7e-1sq** [comment]
At present, I still fail to compile. I have tried other systems, and the problem is still the same. Did you encounter it when compiling?

**Comment by 0x7e-1sq** [comment]
Thanks, the compilation passed, but executed under /src/bin
sudo tc filter add dev enp0s3 egress bpf direct - action obj bin/tc.o sec classifier/egress
will prompt:
what mode is "-"?
unable to parse bpf command line
Are bpf and bpftool the same tool?

**Comment by 0x7e-1sq** [comment]
> 

apt install build-essential libncurses5-dev make g++ gcc zlib zlib-dev libelf libelf-dev libclang-dev clang-11 lldb-11 lld-11 libc++-11-dev libc++abi-11-dev libc6-dev-i386 llvm openssl libssl-dev libbpf-dev

This is the dependency package I used when compiling, you can take a look

**Comment by h3xduck** [comment]
@yasindce1998 I am moving your issue to a separate thread, since it is an unrelated problem

**Comment by h3xduck** [comment]
Apologies for the issue, there was an extra space in the command. I just updated the README with the correct tc command (tc should be available by default in your system). 

For the record, the tc command is: sudo tc filter add dev <NETWORK_INTERFACE> egress bpf direct-action obj <TC_PROGRAM> sec classifier/egress

**Comment by 0x7e-1sq** [comment]
> Apologies for the issue, there was an extra space in the command. I just updated the README with the correct tc command (tc should be available by default in your system).
> 
> For the record, the tc command is:
> 
> ```
> sudo tc filter add dev <NETWORK_INTERFACE> egress bpf direct-action obj <TC_PROGRAM> sec classifier/egress
> ```
> 
> @0x7e-1sq

I am very happy. According to your prompt, I have completed the compilation and run it, but I did not understand the instructions in your document. Do I want to upload a file to the test server? Then do nc listening on my rookit server?

**Comment by 0x7e-1sq** [comment]
I am very happy. According to your prompt, I have completed the compilation and run it, but I did not understand the instructions in your document. Do I want to upload a file to the test server? Then do nc listening on my rookit server?

@h3xduck

**Comment by h3xduck** [comment]
I'm assuming you want to test the backdoor here:
1) You install the rootkit in the target machine. The backdoor starts automatically.
2) From the rootkit client you can connect to the backdoor by specifying its address.

I am closing the issue since the original problem it has been solved.
